### ISSUE TITLE
ImportError: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found

### ISSUE THREAD

**Issue by jgrundstad** [statgen/pheweb#114]
I'm attempting to process data for a test instance of pheweb, and get this exception at the `pheweb matrix` stage:

```
======= Exception ====
/usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/grundaj/envs/pheweb/lib/python3.6/site-packages/pheweb/load/cffi/_x.abi3.so)

======= Traceback ====
Traceback (most recent call last):
  File "/home/grundaj/envs/pheweb/lib/python3.6/site-packages/pheweb/command_line.py", line 162, in main
    run(sys.argv[1:])
  File "/home/grundaj/envs/pheweb/lib/python3.6/site-packages/pheweb/command_line.py", line 156, in run
    handlers[subcommand](argv[1:])
  File "/home/grundaj/envs/pheweb/lib/python3.6/site-packages/pheweb/command_line.py", line 67, in f
    module.run(argv)
  File "/home/grundaj/envs/pheweb/lib/python3.6/site-packages/pheweb/load/process_assoc_files.py", line 45, in run
    module = importlib.import_module('.{}'.format(script_parts[0]), __package__)
  File "/home/grundaj/envs/pheweb/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/grundaj/envs/pheweb/lib/python3.6/site-packages/pheweb/load/matrix.py", line 4, in <module>
    from .cffi._x import ffi, lib
ImportError: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/grundaj/envs/pheweb/lib/python3.6/site-packages/pheweb/load/cffi/_x.abi3.so)
```

We're currently (conservatively) running v4.8.5 on CentOS 7.4, is 3.4.20 a strict requirement?

Thanks!

**Comment by jgrundstad** [comment]
My mistake, I didn't understand the versioning.  Loading a more recent gcc lib fixed the issue.

**Comment by pjvandehaar** [comment]
Glad it worked for you.  Feel free to report any other issues.
