### ISSUE TITLE
`pheweb qq` error: An exception occurred

### ISSUE THREAD

**Issue by Shicheng-Guo** [statgen/pheweb#138]
I met a problem from `pheweb qq` error reporting with `An exception occurred`, Is there any suggestion? 
```
==> Starting `pheweb qq`

An exception occurred
(Details in /projects/ps/dsci-csb/pheweb/generated-by-pheweb/tmp/exception-2020-07-13T19-38-38.856890)

```
Here is the details of `exception-2020-07-13T19-38-38.856890`:

```
======= Exception ====
No module named 'scipy._lib'

======= Traceback ====
Traceback (most recent call last):
  File "/home/sguo2/bin/miniconda3/lib/python3.7/site-packages/pheweb/command_line.py", line 148, in main
    run(sys.argv[1:])
  File "/home/sguo2/bin/miniconda3/lib/python3.7/site-packages/pheweb/command_line.py", line 142, in run
    handlers[subcommand](argv[1:])
  File "/home/sguo2/bin/miniconda3/lib/python3.7/site-packages/pheweb/command_line.py", line 63, in f
    module.run(argv)
  File "/home/sguo2/bin/miniconda3/lib/python3.7/site-packages/pheweb/load/process_assoc_files.py", line 46, in run
    module = importlib.import_module('.{}'.format(script_parts[0]), __package__)
  File "/home/sguo2/bin/miniconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/sguo2/bin/miniconda3/lib/python3.7/site-packages/pheweb/load/qq.py", line 28, in <module>
    import scipy.stats
  File "/home/sguo2/bin/miniconda3/lib/python3.7/site-packages/scipy/__init__.py", line 70, in <module>
    from ._lib.deprecation import _deprecated
ModuleNotFoundError: No module named 'scipy._lib'

```

Thanks. 

Shicheng

**Comment by pjvandehaar** [comment]
Could you try some of these ideas:
https://stackoverflow.com/questions/50418047/import-error-no-module-named-scipy-lib

If you fix it, I’d appreciate if you’d write what worked here.

**Comment by Shicheng-Guo** [comment]
Thanks Peter. Problem solved. I think it is caused by abnormal data format. After I rebuild the input summary statistic, the error is disappeared. What I learned is we should exactly follow the manual and use the example of the software to test all config process.
