### ISSUE TITLE
"AssertionError" in `pheweb sites -f && pheweb add-rsids && pheweb add-genes`

### ISSUE THREAD

**Issue by Shicheng-Guo** [statgen/pheweb#140]
Hi Peter, 

Do you have any idea bout `AssertionError` in `pheweb sites -f && pheweb add-rsids && pheweb add-genes`

```
(base) [sguo2@comet-ln2 pheweb]$ pheweb sites -f && pheweb add-rsids && pheweb add-genes

An exception occurred
(Details in /projects/ps/dsci-csb/user/sguo2/pheweb/generated-by-pheweb/tmp/exception-2020-07-27T23-41-47.823037)

(base) [sguo2@comet-ln2 pheweb]$ less /projects/dsci-csb/user/sguo2/pheweb/generated-by-pheweb/tmp/exception-2020-07-27T23-41-47.823037
======= Exception ====
```

```
======= Traceback ====
Traceback (most recent call last):
  File "/home/sguo2/bin/miniconda3/lib/python3.7/site-packages/pheweb/command_line.py", line 148, in main
    run(sys.argv[1:])
  File "/home/sguo2/bin/miniconda3/lib/python3.7/site-packages/pheweb/command_line.py", line 142, in run
    handlers[subcommand](argv[1:])
  File "/home/sguo2/bin/miniconda3/lib/python3.7/site-packages/pheweb/command_line.py", line 63, in f
    module.run(argv)
  File "/home/sguo2/bin/miniconda3/lib/python3.7/site-packages/pheweb/load/sites.py", line 36, in run
    manna = MergeManager()
  File "/home/sguo2/bin/miniconda3/lib/python3.7/site-packages/pheweb/load/sites.py", line 83, in __init__
    assert os.path.exists(filepath)
AssertionError

```

**Comment by pjvandehaar** [comment]
It sounds like somehow a file in `generated-by-pheweb/pheno/` went missing, and now pheweb will tell you which if it ever happens again.
