### ISSUE TITLE
Genetic correlations are not shown 

### ISSUE THREAD

**Issue by 11Dmitriy11** [statgen/pheweb#194]
Hello! 
I am using PheWeb 1.3.16
I genedarted pheno-correlations.txt and put it in the same folder as pheno-list.json. I put show_correlations = True in config.py, however the table on the site is empty. Also I tried to delete all NAs but I doesn't help.  Is there anything else I have to do? 
![Screenshot_69](https://user-images.githubusercontent.com/51783229/160246429-929fbfd7-2636-45ab-9172-174878b67327.png)

Best,
Dmitrii

**Comment by pjvandehaar** [comment]
Maybe run `pheweb pheno-correlation`?

**Comment by 11Dmitriy11** [comment]
Thank you! 
I used rg-pipeline to generate pheno-correlations.txt
I run `pheweb pheno-correlation` and got an exception:
======= Exception ====


======= Traceback ====
Traceback (most recent call last):
  File "/nfs/home/dusolcev/.local/lib/python3.8/site-packages/pheweb/command_line.py", line 134, in main
    run(sys.argv[1:])
  File "/nfs/home/dusolcev/.local/lib/python3.8/site-packages/pheweb/command_line.py", line 124, in run
    handlers[subcommand](argv[1:])
  File "/nfs/home/dusolcev/.local/lib/python3.8/site-packages/pheweb/command_line.py", line 62, in f
    module_run(argv)
  File "/nfs/home/dusolcev/.local/lib/python3.8/site-packages/pheweb/load/pheno_correlation.py", line 40, in run
    main(raw_correl_filepath, annotated_correl_filepath)
  File "/nfs/home/dusolcev/.local/lib/python3.8/site-packages/pheweb/load/pheno_correlation.py", line 46, in main
    make_symmetric(raw_filepath, symmetric_filepath)
  File "/nfs/home/dusolcev/.local/lib/python3.8/site-packages/pheweb/load/pheno_correlation.py", line 64, in make_symmetric
    assert header.rstrip().split('\t') == expected_colnames
AssertionError
