### ISSUE TITLE
Variants page is not displayed

### ISSUE THREAD

**Issue by Hiroaki-S-Ri** [statgen/pheweb#201]
Hi,

I use pheweb on the centos7.
・Plot page and region page can be displayed on the web, like the following.
![pheno](https://user-images.githubusercontent.com/78518367/188038817-fd62a189-90d2-46d5-ad18-1fddfd1f2ca0.png)

・but variant page on the web is not displayed, like the following.
![variant](https://user-images.githubusercontent.com/78518367/188039157-a7234375-4a02-4ee9-a49d-3fd7955cd8ce.png)

・And, on the terminal, the following output was obtained.

Exception: geno_id
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pheweb/serve/server.py", line 120, in variant_page
    variant = get_variant(query)
  File "/usr/local/lib/python3.7/site-packages/pheweb/serve/server_utils.py", line 72, in get_variant
    self._matrix_reader = MatrixReader()
  File "/usr/local/lib/python3.7/site-packages/pheweb/file_utils.py", line 260, in __init__
    assert field in parse_utils.fields, field
AssertionError: geno_id
Oh no, something went wrong

Could you tell me how to solve this problem?

**Comment by pjvandehaar** [comment]
What is your pheweb version?  What is in your config.py?  Where did
“geno_id” come from?

**Comment by Hiroaki-S-Ri** [comment]
Pheweb version is 1.3.16. The predecessor originally added geno_id to input data and conf_utils.py's per_variant_fields, but when I upgraded centos pheweb was also upgraded and setting of geno_id was removed. So I added geno_id to parse_utils.py, and solved it.

Thank you.

**Comment by pjvandehaar** [comment]
Great!
