### ISSUE TITLE
"An exception occurred" when I run the command: pheweb serve --open

### ISSUE THREAD

**Issue by ikio3** [statgen/pheweb#213]
I am using pheweb 1.3.16

I am running command pheweb serve --open

the output is "An exception occurred (Details in /Users/my-new-pheweb/generated-by-pheweb/tmp/exception-2023-10-23T19-01-02.921594)"

 The file is showed below:
======= Exception ====
Command '['dig', '+short', 'myip.opendns.com', '@resolver1.opendns.com']' returned non-zero exit status 9.

======= Traceback ====
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/pheweb/command_line.py", line 134, in main
    run(sys.argv[1:])
  File "/opt/anaconda3/lib/python3.9/site-packages/pheweb/command_line.py", line 124, in run
    handlers[subcommand](argv[1:])
  File "/opt/anaconda3/lib/python3.9/site-packages/pheweb/command_line.py", line 69, in serve
    run(argv)
  File "/opt/anaconda3/lib/python3.9/site-packages/pheweb/serve/run.py", line 125, in run
    print_ip(args.port, conf.get_urlprefix())
  File "/opt/anaconda3/lib/python3.9/site-packages/pheweb/serve/run.py", line 64, in print_ip
    ip = get_ip()
  File "/opt/anaconda3/lib/python3.9/site-packages/pheweb/serve/run.py", line 79, in get_ip
    return subprocess.check_output('dig +short myip.opendns.com @resolver1.opendns.com'.split()).strip().decode('ascii')
  File "/opt/anaconda3/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/anaconda3/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dig', '+short', 'myip.opendns.com', '@resolver1.opendns.com']' returned non-zero exit status 9.

my config.py includes:
hg_builf_number=19

**Comment by ikio3** [comment]
At the same time, I also run pheweb serve, it returns: 
[2023-10-23 19:03:14 +0800] [10066] [INFO] Starting gunicorn 20.0.4
[2023-10-23 19:03:14 +0800] [10066] [ERROR] Connection in use: ('0.0.0.0', 5000)

**Comment by pjvandehaar** [comment]
MacOS sometimes uses port 5000 for its own software.  Try “pheweb serve
—port=8080”.

**Comment by pjvandehaar** [comment]
It sounds like myip.opendns.com no longer returns an IP address. It needs to be replaced with "curl ifconfig.me/ip".
